# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GooglePlaces' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GooglePlaces', '8.3.0'

  # Pods for GooglePlaces

  target 'GooglePlacesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GooglePlacesUITests' do
    # Pods for testing
  end
  
    pod 'GooglePlaces', '8.3.0'

end
